add different stuff

diff --git a/dot_local/bin/executable_cheat b/dot_local/bin/executable_cheat
--- a/dot_local/bin/executable_cheat
+++ b/dot_local/bin/executable_cheat
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# shellcheck source=/dev/null
+source "$HOME/.local/bin/__common.sh"
+
 cachedir="$HOME/.cache/cheat.sh/"
 url="https://cheat.sh/$*"
 
@@ -9,31 +12,26 @@ ping -c 1 -w 1 cheat.sh >/dev/null 2>&1
 exitstatus=$?
 
 if [[ $exitstatus -ne 0 ]]; then
-    echo "Unable to connect to cheat.sh, please check your internet connection."
+    log_warn "Unable to connect to cheat.sh, please check your internet connection."
 
     if [ -f "$cachedir/$*" ]; then
-        echo "Using cached version. Last updated: $(stat -c %y "$cachedir/$*")"
-        cat "$cachedir/$*"
+        log_info "Using cached version. Last updated: $(stat -c %y "$cachedir/$*")"
+        pager "$cachedir/$*"
         exit 0
+    else
+        log_error "Page requested not in cache."
+        exit 1
     fi
-
-    echo "Page requested not in cache."
-    exit 1
 fi
 
-echo "Opening $url"
+log_info "Opening $url"
 page=$(curl -s "$url")
 
 if ! echo "$page" | grep -ivq "Unknown topic."; then
-    echo "$page"
+    pager "$page"
     exit 1
 fi
 
 echo "$page" >"$cachedir/$*"
 
-if test "$(echo "$page" | wc -l)" -gt "$(tput lines)"; then
-    echo "$page" | less -R
-    echo "$page"
-else
-    echo -e "$page"
-fi
+pager "$page"
