Updates to camera-defaults

diff --git a/dot_local/bin/executable_camera-defaults b/dot_local/bin/executable_camera-defaults
--- a/dot_local/bin/executable_camera-defaults
+++ b/dot_local/bin/executable_camera-defaults
@@ -5,6 +5,10 @@
 # shellcheck source=executable___common.sh
 source "$HOME/.local/bin/__common.sh"
 
+readonly DEFAULT_NAME="Logi 4K Stream Edition"
+readonly FALSE=0
+readonly TRUE=1
+
 readonly dependencies=(
     "v4l2-ctl:Setting options"
     "grep:Matching device"
@@ -16,7 +20,10 @@ readonly dependencies=(
 check_dependencies "${dependencies[@]}"
 
 if [[ -z "${DEVICE:-}" ]]; then
-    DEVICE=$(v4l2-ctl --list-devices | grep "Logi 4K Stream Edition" -A1 | tail -n1 | awk '{ print $1 }')
+    if ! DEVICE=$(v4l2-ctl --list-devices | grep "$DEFAULT_NAME" -A1 | tail -n1 | awk '{ print $1 }'); then
+        log_error "Failed to find device with name '$DEFAULT_NAME'"
+        exit 1
+    fi
 fi
 
 # Bool: 0=False; 1=True
@@ -24,29 +31,35 @@ fi
 readonly args=(
     --device "$DEVICE"
 
-    --set-ctrl brightness=100
-    --set-ctrl contrast=140
-    --set-ctrl saturation=130
-    --set-ctrl gain=90
-    --set-ctrl power_line_frequency=1           # 0=Disabled; 1=50Hz; 2=60Hz
-    --set-ctrl white_balance_automatic=0        # Bool
-    --set-ctrl white_balance_temperature=3600
-    --set-ctrl sharpness=130
-    --set-ctrl backlight_compensation=1         # Bool
-    --set-ctrl auto_exposure=1                  # 1=Manual; 3=Aperture Priority
-    --set-ctrl exposure_dynamic_framerate=0     # Bool
-    --set-ctrl exposure_time_absolute=300
+    --set-ctrl brightness=100                     # 0-255
+    --set-ctrl contrast=135                       # 0-255
+    --set-ctrl saturation=125                     # 0-255
+    --set-ctrl gain=80                            # 0-255
+    --set-ctrl power_line_frequency=1             # 0=Disabled; 1=50Hz; 2=60Hz
+    --set-ctrl white_balance_automatic="$FALSE"
+    --set-ctrl white_balance_temperature=3300     # Kelvin
+    --set-ctrl sharpness=90                       # 0-255
+    --set-ctrl backlight_compensation="$TRUE"
+    --set-ctrl auto_exposure=1                    # 1=Manual; 3=Aperture Priority
+    --set-ctrl exposure_dynamic_framerate="$FALSE"
+    --set-ctrl exposure_time_absolute=330
     --set-ctrl pan_absolute=0
     --set-ctrl tilt_absolute=0
-    # --set-ctrl focus_absolute=0               # Focus can't be set at the same time as focus_automatic_continous
-    --set-ctrl focus_automatic_continuous=1     # Bool
-    --set-ctrl zoom_absolute=130
+    # --set-ctrl focus_absolute=0                # Focus can't be set at the same time as focus_automatic_continous
+    --set-ctrl focus_automatic_continuous="$TRUE"
+    --set-ctrl zoom_absolute=130                 # 100-500%
 )
 
-log_info "Set default options"
-
-v4l2-ctl "${args[@]}"
-notify-send \
-    --app-name="Webcam" \
-    --icon="camera" \
-    "Set default options"
+if ! v4l2-ctl "${args[@]}"; then
+    log_error "Failed to set default options"
+    notify-send \
+        --app-name="Webcam" \
+        --icon="camera" \
+        "Failed to set default options"
+else
+    log_info "Set default options"
+    notify-send \
+        --app-name="Webcam" \
+        --icon="camera" \
+        "Set default options"
+fi
